//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.gnu.glpk {

public class glp_arc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal glp_arc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(glp_arc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~glp_arc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GLPKPINVOKE.delete_glp_arc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public glp_vertex tail {
    set {
      GLPKPINVOKE.glp_arc_tail_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_vertex.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_tail_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_vertex(cPtr, false);
    }
  
  }

  public glp_vertex head {
    set {
      GLPKPINVOKE.glp_arc_head_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_vertex.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_head_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_vertex(cPtr, false);
    }
  
  }

  public SWIGTYPE_p_void data {
    set {
      GLPKPINVOKE.glp_arc_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_void temp {
    set {
      GLPKPINVOKE.glp_arc_temp_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_temp_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public glp_arc t_prev {
    set {
      GLPKPINVOKE.glp_arc_t_prev_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_arc.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_t_prev_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_arc(cPtr, false);
    }
  
  }

  public glp_arc t_next {
    set {
      GLPKPINVOKE.glp_arc_t_next_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_arc.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_t_next_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_arc(cPtr, false);
    }
  
  }

  public glp_arc h_prev {
    set {
      GLPKPINVOKE.glp_arc_h_prev_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_arc.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_h_prev_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_arc(cPtr, false);
    }
  
  }

  public glp_arc h_next {
    set {
      GLPKPINVOKE.glp_arc_h_next_set(swigCPtr, global::System.Runtime.InteropServices.HandleRef.ToIntPtr(glp_arc.getCPtr(value)));
      if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = GLPKPINVOKE.glp_arc_h_next_get(swigCPtr);
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
      return (cPtr == global::System.IntPtr.Zero) ? null : new glp_arc(cPtr, false);
    }
  
  }

  public glp_arc() : this(GLPKPINVOKE.new_glp_arc(), true) {
    if (GLPKPINVOKE.SWIGPendingException.Pending) throw GLPKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
